### ISSUE TITLE
List of projects being served with docsrv

### ISSUE THREAD

**Issue by dpordomingo** [src-d/docs#1]
For the [12-O release](https://github.com/src-d/backlog/issues/1027) it will be needed the documentation for the following proyects under the following domains:

- `engine.sourced.tech` -> [src-d/spark-api](https://github.com/src-d/spark-api)
- `siva.sourced.tech` -> [src-d/go-siva](https://github.com/src-d/go-siva) + [src-d/siva-java](https://github.com/src-d/siva-java)
- `enry.sourced.tech` -> [src-d/enry](https://github.com/src-d/enry)
- `bblf.sh` -> [bblfsh/bblfshd](https://github.com/bblfsh/bblfshd) + [bblfsh/sdk](https://github.com/bblfsh/sdk) + [bblfsh/dashboard](https://github.com/bblfsh/dashboard) + [bblfsh/client-scala](https://github.com/bblfsh/client-scala)

**Comment by dpordomingo** [comment]
Since `docsrv` was not designed for serving the documentation for many projects under the same domain, the first release will work as it follows:
`go-siva.sourced.tech` -> [src-d/go-siva](https://github.com/src-d/go-siva)
`bblf.sh` -> [bblfsh/bblfshd](https://github.com/bblfsh/bblfshd)

**Comment by dpordomingo** [comment]
Since the domain `doc.bblf.sh` is already used for the hand-made [bblfsh documentation](https://github.com/bblfsh/documentation), I updated this issue desc with the main domain that will be used for the bbfsh docs served by our `docsrv`:
- `bblf.sh` -> [bblfsh/bblfshd](https://github.com/bblfsh/bblfshd) + [bblfsh/sdk](https://github.com/bblfsh/sdk) + [bblfsh/dashboard](https://github.com/bblfsh/dashboard) + [bblfsh/client-scala](https://github.com/bblfsh/client-scala)

/cc @smeruelo @rporres

**Comment by dpordomingo** [comment]
@smeruelo I changed the issue description to reflect that the final name given to `spark-api` is `engine`, so then, the domain for its doc will be: `engine.sourced.tech`.

As confirmed by @marnovo via Slack, the hostname for siva will be `siva.sourced.tech`.

With that changes in mind, the list of domains for the docs is:
- `engine.sourced.tech`
- `siva.sourced.tech`
- `enry.sourced.tech`
- `bblf.sh`

**Comment by dpordomingo** [comment]
It's not urgent, but it would help me if we could have the following domains:
- `sdk.bblf.sh`
- `dashboard.bblf.sh`
- `client-scala.bblf.sh`

They are not yet confirmed, but having them would help me to test the contents

**Comment by smeruelo** [comment]
https://github.com/src-d/infrastructure/pull/21

**Comment by rporres** [comment]
@dpordomingo If those domains are not part of the launch, we won't create them now. Please submit a request once we're done.
