### ISSUE TITLE
High Security issues in docsrv images

### ISSUE THREAD

**Issue by dpordomingo** [src-d/docs#2]
I just pushed them, and quay complaint about some high security issues:
- https://quay.io/repository/srcd/docs?tab=tags
- https://quay.io/repository/srcd/docsrv?tab=tags

I need assistance to fix them

**Comment by rporres** [comment]
Hi @dpordomingo Caddyfile uses the latest version of alpine linux (3.6) https://github.com/abiosoft/caddy-docker/blob/master/Dockerfile which has  the version that solves the vulnerabilities. See

* http://bugs.alpinelinux.org/issues/7357
* https://pkgs.alpinelinux.org/package/edge/main/x86/zlib

My bet is that you're building locally the `docs` file using an old version of the Caddy container. Try pulling again `abiosoft/caddy`

**Comment by dpordomingo** [comment]
That was the problem; thank you!
