### ISSUE TITLE
Deploy into prod

### ISSUE THREAD

**Issue by dpordomingo** [src-d/docs#4]
It would be needed to deploy this into staging for the repos given by https://github.com/src-d/docs/issues/1

After the PR https://github.com/src-d/docs/pull/3 it can be generated a functional `docs` image extending from a `docsrv` image.
I uploaded both into quay:
- *docs* (final) https://quay.io/repository/srcd/docs?tab=tags
- *docsrv* (base) https://quay.io/repository/srcd/docsrv?tab=tags

If you try with http://go-git.sourced.tech it should take only a few seconds.

If you try with http://spark-api.sourced.tech it can take ~15mins to generate the api docs because it is needed to fetch many scala and python dependencies. Do not refresh till the page is fully loaded.

**Comment by smeruelo** [comment]
Please provide a backend point that always returns a 200 code, so kubernetes can use it as a health check.

**Comment by dpordomingo** [comment]
healthcheck url:
- `/healthcheck`

images:
- `quay.io/srcd/docs:v0.0.1`
- `quay.io/srcd/docsrv:v0.0.1`

**Comment by smeruelo** [comment]
go-git was not included en first request (#1), added (https://github.com/src-d/infrastructure/pull/19)

**Comment by dpordomingo** [comment]
it was pushed a new image with the healthcheck, as given by https://github.com/src-d/docs/pull/5
`quay.io/srcd/docs:e3ff5c6`, made from commit e3ff5c6

**Comment by dpordomingo** [comment]
New image
`quay.io/srcd/docs:47b3179` from 47b3179

**Comment by smeruelo** [comment]
Version `47b3179` deployed in prod.

**Comment by dpordomingo** [comment]
I'm not sure if we should fix [the security issues](https://github.com/src-d/docs/issues/2) before going to public-prod with this.
@src-d/infrastructure Let me know if I should take care about it, because I'd need to investigate about it, and it may impact my agenda.

**Comment by rporres** [comment]
@dpordomingo I've commented in the security issues ticket. https://github.com/src-d/docs/issues/2

Can you take a look?

**Comment by dpordomingo** [comment]
Version `41a6c6e` deployed in prod.

Security problem fixed

**Comment by dpordomingo** [comment]
Last image already tested in Prod, with the four agreed domains:
`quay.io/srcd/docs:63a31d0` build with commit https://github.com/src-d/docs/commit/63a31d0
